name: Daily Memory Cron

on:
  schedule:
    - cron: '0 3 * * *' # täglich um 03:00 UTC
  workflow_dispatch: {}

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron endpoint
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$APP_URL" ] || [ -z "$CRON_SECRET" ]; then
            echo "Missing APP_URL or CRON_SECRET secrets" >&2
            exit 1
          fi
          curl -sS -X POST "$APP_URL/api/memory/cron?secret=$CRON_SECRET" -H 'Content-Type: application/json' -d '{}' \
            | jq '.' || true


